[targets]
client1 ansible_host=20.66.115.14 ansible_user=azureuser ansible_become=yes ansible_become_method=sudo ansible_become_password=faridah@007007 ansible_password=faridah@007007 ansible_ssh_common_args='-o PreferredAuthentications=password -o PubkeyAuthentication=no'
