---
<<<<<<< HEAD
- name: Apply Security Baseline
  hosts: all
  become: yes

  tasks:
    - name: Ensure firewall is enabled
      service:
        name: ufw
        state: started
        enabled: yes

    - name: Disable root SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: restart ssh

  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted
=======
- name: Security Baseline Scan
  hosts: localhost
  gather_facts: yes
  become: yes

  tasks:
    - name: Check world-writable files
      shell: find / -type f -perm -0002 2>/dev/null | head -n 20
      register: ww_files

    - name: Check running services
      command: systemctl list-units --type=service --state=running
      register: services

    - name: Check SSH configuration (safe mode)
      shell: |
        if [ -f /etc/ssh/sshd_config ]; then
          cat /etc/ssh/sshd_config
        else
          echo "SSH server not installed on this system."
        fi
      register: ssh_config

    - name: Display security scan results
      debug:
        msg: |
          === WORLD WRITABLE FILES ===
          {{ ww_files.stdout }}

          === RUNNING SERVICES ===
          {{ services.stdout }}

          === SSH CONFIGURATION ===
          {{ ssh_config.stdout }}

>>>>>>> d9628c2 (Deploying NimbusOps backend and frontend)
