<<<<<<< HEAD
---
- name: ClientA Health Check
  hosts: all
  gather_facts: yes

  tasks:
    - name: Check disk usage
      command: df -h
      register: disk_output

    - name: Show disk usage
      debug:
        var: disk_output.stdout

    - name: Check memory usage
      command: free -m
      register: mem_output

    - name: Show memory usage
      debug:
        var: mem_output.stdout

    - name: Check system uptime
      command: uptime
      register: uptime_output

    - name: Show uptime
      debug:
        var: uptime_output.stdout



=======
---
- name: System Health Check
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Check disk usage
      command: df -h
      register: disk

    - name: Check memory usage
      command: free -m
      register: memory

    - name: Check system uptime
      command: uptime
      register: uptime_out

    - name: Display health check results
      debug:
        msg: |
          === DISK USAGE ===
          {{ disk.stdout }}

          === MEMORY USAGE ===
          {{ memory.stdout }}

          === SYSTEM UPTIME ===
          {{ uptime_out.stdout }}

>>>>>>> d9628c2 (Deploying NimbusOps backend and frontend)
