---
- name: ClientA Health Check
  hosts: all
  gather_facts: yes

  tasks:
    - name: Check disk usage
      command: df -h
      register: disk_output

    - name: Show disk usage
      debug:
        var: disk_output.stdout

    - name: Check memory usage
      command: free -m
      register: mem_output

    - name: Show memory usage
      debug:
        var: mem_output.stdout

    - name: Check system uptime
      command: uptime
      register: uptime_output

    - name: Show uptime
      debug:
        var: uptime_output.stdout


